### ISSUE TITLE
Permission denied - /media/qroot/2b1cb2d0-28b6-47aa-9073-5c9702adca0d/usr/share/.bundle

### ISSUE THREAD

**Issue by Mualter** [rubygems/bundler-gem#1]
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?
  
  I ran the command `/usr/local/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to be installed
- What happened instead?
  
  Instead, what actually happened was this error came out.

Error details

```
Errno::EACCES: Permission denied - /media/qroot/2b1cb2d0-28b6-47aa-9073-5c9702adca0d/usr/share/.bundle
  /usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
  /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
  /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
  /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
  /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
  /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
  /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:208:in `set_key'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:31:in `[]='
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:199:in `set_array'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/settings.rb:117:in `without='
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli/install.rb:96:in `run'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:162:in `install'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
  /var/lib/gems/1.9.1/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'
```

Environment

```
Bundler   1.10.6
Rubygems  1.8.23
Ruby      1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Git       1.9.1
```

Bundler settings

```
without
  Set for your local app (/media/qroot/2b1cb2d0-28b6-47aa-9073-5c9702adca0d/usr/share/.bundle/config): "test"
  Set for the current user (/home/qroot/.bundle/config): "test"
```

--- TEMPLATE END ----------------------------------------------------------------

**Comment by Mualter** [comment]
The command that i actually ran was $sudo gem install bundler && bundle install --without test
in /usr/share directory

**Comment by segiddins** [comment]
Do you have write permissions for that directory?

**Comment by Mualter** [comment]
Solved by having that permissions for the directory, thanks.
